[package]
name = "rust_core_bp"
version = "0.1.0"
edition = "2024"


[lib]
path = "src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rust_core_bp"

[dependencies]
actix-web = "4.11.0"
tokio = { version = "1.46.1", features = ["full"] }

